version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-visualizer
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1